### ISSUE TITLE
only want data from the last 5 seconds before launch

### ISSUE THREAD

**Issue by mallamacimj** [Terrapin-Rocket-Team/Multi-Mission-Flight-Software#17]

**Comment by mallamacimj** [comment]
Implement a circular buffer - talk to avionics about how they are doing it

**Comment by varun-un** [comment]
Do we still want this? Or at least the option for this?

**Comment by mallamacimj** [comment]
Yes. Doesn't have be 5 seconds. Circular buffer is fine.

**Comment by DrewBrandt** [comment]
I think a PRE_FLIGHT_BUFFER_TIME const in the constants file might make sense here so that different teams can keep as much data from pre-flight as they want.
