### ISSUE TITLE
add dependencies needed

### ISSUE THREAD

**Issue by mallamacimj** [Terrapin-Rocket-Team/Multi-Mission-Flight-Software#20]

**Comment by mallamacimj** [comment]
to the wiki

**Comment by DrewBrandt** [comment]
Can you explain a little bit more what you mean by this?

**Comment by mallamacimj** [comment]
If we are including some already completed sensor implementations such as the bmp280 for example then the adafruit library for the bmp would need to called out as a dependency somewhere.
