### ISSUE TITLE
gps haversine

### ISSUE THREAD

**Issue by mallamacimj** [Terrapin-Rocket-Team/Multi-Mission-Flight-Software#29]
Need to figure out how to run the haversine only once 5 gps satellites have been locked so that it gets a good x and y position. possibly ask avionics about it

**Comment by DrewBrandt** [comment]
Avionics' version does this for the MAX m10s (now implemented here)

**Comment by DrewBrandt** [comment]
I was wrong. We use a flat earth model, this is not implemented.
