### ISSUE TITLE
Use Pure Virtual Functions in Sensors

### ISSUE THREAD

**Issue by varun-un** [Terrapin-Rocket-Team/Multi-Mission-Flight-Software#56]
Some of the functions in files like `Barometer.h` should be pure virtual functions if they are only meant to be overridden, and so this should be changed.

**Comment by DrewBrandt** [comment]
Can you provide an example of what you mean

**Comment by DrewBrandt** [comment]
In #51 I changed the `read()` and `init()` to protected so they can no longer be accessed from outside the Sensor stack of classes.
